#!/usr/bin/env python3
import json
import sys
import os
os_path = os.path.dirname(os.getcwd()) + '/Fish/Common'
sys.path.append(os_path)
from Board import Board
from State import State

def parser(input_stream):
    """
    Parse the given input string from the client.

    :input_stream: string       a string representing the JSON input from client

    :return: JSON object
    """
    ordered_output = []
    maybe_json = ''
    for line in input_stream:
        strip_input = line.strip()
        maybe_json = maybe_json + strip_input
    return json.loads(maybe_json)

def main():
    board_json = parser(sys.stdin)
    # create the board from input
    board_array = board_json['board']
    board = Board(len(board_array), len(board_array[0]))
    board.create_board_from_json(board_array)
    # get all reachable positions from given position
    position = board_json['position']
    reachable_posns = board.get_all_reachable_posn(position[0], position[1])
    print(len(reachable_posns))

main()
