#!/usr/bin/env python3

from Fish.Remote.server import FishServer

import sys


def main(port):
    """
    Create a Fish.com server, sign up players, and run a tournament.
    """
    server = FishServer(('localhost', port))
    if server.run_signup():
        server.run_tournament()
    server.shutdown()


if __name__ == '__main__':
    main(int(sys.argv[1]))
